# Provide the following:
#   - Event name
#   - When the event should run
#   - What jobs to execute
#   - What steps within each job

# Event name
name: on_push

# When the event should run
on:
  push:
    branches:
      - "**" # This will run on all branches and must be quoted to be handled by yaml

# What jobs to execute
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env: # Configure environment variables used in the code
      RUNNER_OS: true
      HEADLESS_CHROME: true # Required for CI

    # steps within each job
    steps:
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV # $GITHUB_ENV can be used to store things between steps
      - uses: actions/checkout@v2 # Checkout repository under $GITHUB_WORKSPACE so the workflow can access it
      - uses: actions/setup-java@v2 # Install Java
        with:
          distribution: 'zulu'
          java-version: 16
      - name: Run tests with maven
        working-directory: webdriver_java # Change the working directory
        run: mvn test # Run maven test
      - name: Collect build data
        if: always() # run always
        run: expr $(date +%s) - ${START_TIME}

